title:  MWV
subtitle: Catalogue of the Works of Felix Mendelssohn Bartholdy

email: info@rism.digital
baseurl: "/rism-catalogue-mwv"

sponsors:
  - url: https://fr.wikipedia.org/wiki/Licence_Creative_Commons
    logo: CC_license.png

languages: ["en", "de"]
default_lang: "en"
exclude_from_localization: ["assets", "javascript", "rism-online-renderer", "images", "css", "README.md"]
parallel_localization: false
lang_from_path: false
sass:
  sourcemap: never

theme: rism-catalogue-theme

rism_catalogue: "publications/30025296"